# Generated by Django 6.1.1 on 2026-09-13 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagApp', '0003_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('category', models.CharField(choices=[('Local', 'Within Nyeri Town (Free Meetup)'), ('2NK', '2NK Parcel Services'), ('Other', 'Other Arrangements (Call to Agree)')], default='2NK', max_length=20)),
                ('requires_waybill', models.BooleanField(default=True, help_text='True for 2NK, False for Meetups/Riders')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='2NK Waybill Number', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bagApp.shippinglocation'),
        ),
    ]
