# Generated by Django 6.1.1 on 2026-09-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagApp', '0004_shippinglocation_order_delivery_fee_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_notes',
            field=models.CharField(blank=True, help_text="Customer's exact town and transport choice", max_length=255, null=True),
        ),
    ]
