# Generated by Django 6.1.1 on 2026-09-14 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagApp', '0006_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, help_text='Circular image for the homepage', null=True, upload_to='categories/')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='color_group',
            field=models.CharField(choices=[('Blacks/Greys', '⚫ Blacks & Greys'), ('Browns/Tans', '🟤 Browns & Tans'), ('Whites/Creams', '⚪ Whites & Creams'), ('Brights/Bolds', '🔴 Brights & Bolds'), ('Other', '✨ Other Colors')], default='Blacks/Greys', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='is_popular',
            field=models.BooleanField(default=False, help_text="Check this to feature the bag in the 'Popular' section."),
        ),
        migrations.AddField(
            model_name='product',
            name='is_trending',
            field=models.BooleanField(default=False, help_text="Check this to show the bag in the 'Trending' section on the homepage."),
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Set this to show a strike-through price and a SALE badge.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='bagApp.category'),
        ),
    ]
