# Generated by Django 6.1.1 on 2026-09-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagApp', '0007_category_product_color_group_product_is_popular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
